#!/bin/bash
###############################################################################
# Copyright (c) 2017-2018 Koren Lev (Cisco Systems),                          #
# Yaron Yogev (Cisco Systems), Ilia Abashin (Cisco Systems) and others        #
#                                                                             #
# All rights reserved. This program and the accompanying materials            #
# are made available under the terms of the Apache License, Version 2.0       #
# which accompanies this distribution, and is available at                    #
# http://www.apache.org/licenses/LICENSE-2.0                                  #
###############################################################################

set -e

# build the ui image, it is used to build the new meteor app from recent front-end code:
IMAGE_NAME=${1:-"korenlev/calipso"}
#HTTP_PROXY=${2:-"http://10.56.20.15:8080"}
printf "\n[-] Building the new meteor app $IMAGE_NAME:ui-v2 from your local source...\n\n"
#sudo docker build --build-arg HTTP_PROXY=$HTTP_PROXY --build-arg HTTPS_PROXY=$HTTP_PROXY --build-arg http_proxy=$HTTP_PROXY --build-arg https_proxy=$HTTP_PROXY -f ./Dockerfile -t $IMAGE_NAME:ui-v2 .
sudo docker build -f ./Dockerfile -t $IMAGE_NAME:ui-v2 .
